//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bim.FamilyManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bim.FamilyManager.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new preview image from the current view..
        /// </summary>
        public static string Command_CreatePreviewImage_Description {
            get {
                return ResourceManager.GetString("Command.CreatePreviewImage.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update preview.
        /// </summary>
        public static string Command_CreatePreviewImage_Name {
            get {
                return ResourceManager.GetString("Command.CreatePreviewImage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///preview.
        /// </summary>
        public static string Command_CreatePreviewImage_Text {
            get {
                return ResourceManager.GetString("Command.CreatePreviewImage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Family Manager..
        /// </summary>
        public static string Command_OpenFamilyManager_Description {
            get {
                return ResourceManager.GetString("Command.OpenFamilyManager.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Family Manager settings.
        /// </summary>
        public static string Command_OpenFamilyManager_Name {
            get {
                return ResourceManager.GetString("Command.OpenFamilyManager.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Command_OpenFamilyManager_Text {
            get {
                return ResourceManager.GetString("Command.OpenFamilyManager.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Family Manager settings..
        /// </summary>
        public static string Command_OpenFamilyManagerSettings_Description {
            get {
                return ResourceManager.GetString("Command.OpenFamilyManagerSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Family Manager.
        /// </summary>
        public static string Command_OpenFamilyManagerSettings_Name {
            get {
                return ResourceManager.GetString("Command.OpenFamilyManagerSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Command_OpenFamilyManagerSettings_Text {
            get {
                return ResourceManager.GetString("Command.OpenFamilyManagerSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Manager.
        /// </summary>
        public static string Panel_Name {
            get {
                return ResourceManager.GetString("Panel.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scotec.
        /// </summary>
        public static string Tab_Name {
            get {
                return ResourceManager.GetString("Tab.Name", resourceCulture);
            }
        }
    }
}
