//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bim.FamilyManager.Source.Directory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bim.FamilyManager.Source.Directory.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open folder browser..
        /// </summary>
        public static string DirectorySourceSettings_Button_SelectFolder {
            get {
                return ResourceManager.GetString("DirectorySourceSettings.Button.SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DirectorySourceSettings_Text_Active {
            get {
                return ResourceManager.GetString("DirectorySourceSettings.Text.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view allows you to configure a directory-based source for Revit family files. Enter a name for the source and select the folder containing your family files. You can activate or deactivate this source as needed. Use the folder button to browse and select the directory. These settings help organize and manage your family sources efficiently within the application..
        /// </summary>
        public static string DirectorySourceSettings_Text_Description {
            get {
                return ResourceManager.GetString("DirectorySourceSettings.Text.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string DirectorySourceSettings_Text_Directory {
            get {
                return ResourceManager.GetString("DirectorySourceSettings.Text.Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source directory.
        /// </summary>
        public static string DirectorySourceSettings_Text_Directory_Watermark {
            get {
                return ResourceManager.GetString("DirectorySourceSettings.Text.Directory.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DirectorySourceSettings_Text_Name {
            get {
                return ResourceManager.GetString("DirectorySourceSettings.Text.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter family source name.
        /// </summary>
        public static string DirectorySourceSettings_Text_Name_Watermark {
            get {
                return ResourceManager.GetString("DirectorySourceSettings.Text.Name.Watermark", resourceCulture);
            }
        }
    }
}
