//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bim.FamilyManager.Ui.FamilyNavigator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bim.FamilyManager.Ui.FamilyNavigator.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this family in the Family Editor..
        /// </summary>
        public static string Family_Button_Edit {
            get {
                return ResourceManager.GetString("Family.Button.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the family into the active document..
        /// </summary>
        public static string Family_Button_Load {
            get {
                return ResourceManager.GetString("Family.Button.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this family from the active document..
        /// </summary>
        public static string Family_Button_Remove {
            get {
                return ResourceManager.GetString("Family.Button.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family is present in the active document..
        /// </summary>
        public static string Family_Icon_Imported {
            get {
                return ResourceManager.GetString("Family.Icon.Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family is not present in the active document..
        /// </summary>
        public static string Family_Icon_NotImported {
            get {
                return ResourceManager.GetString("Family.Icon.NotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go up one level..
        /// </summary>
        public static string FamilyManager_Button_Back {
            get {
                return ResourceManager.GetString("FamilyManager.Button.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to root (all family sources)..
        /// </summary>
        public static string FamilyManager_Button_Home {
            get {
                return ResourceManager.GetString("FamilyManager.Button.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all family sources..
        /// </summary>
        public static string FamilyManager_Button_Refresh {
            get {
                return ResourceManager.GetString("FamilyManager.Button.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Family Manager settings..
        /// </summary>
        public static string FamilyManager_Button_Settings {
            get {
                return ResourceManager.GetString("FamilyManager.Button.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Navigator.
        /// </summary>
        public static string LayoutSettings_LayoutName {
            get {
                return ResourceManager.GetString("LayoutSettings.LayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content height.
        /// </summary>
        public static string LayoutSettings_Text_ContentHeight {
            get {
                return ResourceManager.GetString("LayoutSettings.Text.ContentHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show family preview.
        /// </summary>
        public static string LayoutSettings_Text_ShowImage {
            get {
                return ResourceManager.GetString("LayoutSettings.Text.ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show family name.
        /// </summary>
        public static string LayoutSettings_Text_ShowName {
            get {
                return ResourceManager.GetString("LayoutSettings.Text.ShowName", resourceCulture);
            }
        }
    }
}
