//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bim.FamilyManager.Source.AzureStorage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bim.FamilyManager.Source.AzureStorage.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_Active {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_ClientId {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter client ID.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_ClientId_Watermark {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.ClientId.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container name.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_ContainerName {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.ContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter container name.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_ContainerName_Watermark {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.ContainerName.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view allows you to configure an Azure Storage source for Revit family files. Enter the necessary connection details, such as the storage account and container information, to access your files stored in Azure. You can activate or deactivate this source as needed. Use these settings to securely manage and organize your cloud-based family sources within the application..
        /// </summary>
        public static string AzureStorageSourceSettings_Text_Description {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint url.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_Endpoint {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter container name.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_Endpoint_Watermark {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.Endpoint.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_Name {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter family source name.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_Name_Watermark {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.Name.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_RootPath {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.RootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter root path.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_RootPath_Watermark {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.RootPath.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as:.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_SignedInAs {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.SignedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_TenantId {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tenant ID.
        /// </summary>
        public static string AzureStorageSourceSettings_Text_TenantId_Watermark {
            get {
                return ResourceManager.GetString("AzureStorageSourceSettings.Text.TenantId.Watermark", resourceCulture);
            }
        }
    }
}
