//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bim.FamilyManager.Ui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bim.FamilyManager.Ui.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create preview images.
        /// </summary>
        public static string Command_CreatePreviewImages_Name {
            get {
                return ResourceManager.GetString("Command.CreatePreviewImages.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview images for the family were generated successfully..
        /// </summary>
        public static string Command_CreatePreviewImages_Notification_Success {
            get {
                return ResourceManager.GetString("Command.CreatePreviewImages.Notification.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the family to the family source. Please ensure the destination is accessible and writable..
        /// </summary>
        public static string DirectorySource_Message_Save_Error {
            get {
                return ResourceManager.GetString("DirectorySource.Message.Save.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family was saved to the family source..
        /// </summary>
        public static string DirectorySource_Message_Save_Success {
            get {
                return ResourceManager.GetString("DirectorySource.Message.Save.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string DisplaySettings_Text_Layout {
            get {
                return ResourceManager.GetString("DisplaySettings.Text.Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view lets you select and configure the layout for the Family Manager. Choose a layout from the list and adjust its settings as needed. When you press Save, your changes will be saved and the selected layout will become active..
        /// </summary>
        public static string DisplaySettings_View_Description {
            get {
                return ResourceManager.GetString("DisplaySettings.View.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this family in the Family Editor..
        /// </summary>
        public static string Family_Button_Edit {
            get {
                return ResourceManager.GetString("Family.Button.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the family into the active document..
        /// </summary>
        public static string Family_Button_Load {
            get {
                return ResourceManager.GetString("Family.Button.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this family from the active document..
        /// </summary>
        public static string Family_Button_Remove {
            get {
                return ResourceManager.GetString("Family.Button.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family is present in the active document..
        /// </summary>
        public static string Family_Icon_Imported {
            get {
                return ResourceManager.GetString("Family.Icon.Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family is not present in the active document..
        /// </summary>
        public static string Family_Icon_NotImported {
            get {
                return ResourceManager.GetString("Family.Icon.NotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a symbol to place..
        /// </summary>
        public static string FamilyDropWindow_SelectionText {
            get {
                return ResourceManager.GetString("FamilyDropWindow.SelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a symbol to place..
        /// </summary>
        public static string FamilyDropWindow_SelectionText1 {
            get {
                return ResourceManager.GetString("FamilyDropWindow.SelectionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a symbol to place..
        /// </summary>
        public static string FamilyDropWindow_SelectionText2 {
            get {
                return ResourceManager.GetString("FamilyDropWindow.SelectionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place symbol....
        /// </summary>
        public static string FamilyDropWindow_Title {
            get {
                return ResourceManager.GetString("FamilyDropWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bim.FamilyManager.
        /// </summary>
        public static string FamilyManager_Name {
            get {
                return ResourceManager.GetString("FamilyManager.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string FamilySourceSettings_Button_Add {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Button.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FamilySourceSettings_Button_Cancel {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string FamilySourceSettings_Button_Edit {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Button.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string FamilySourceSettings_Button_Ok {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Button.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string FamilySourceSettings_Button_Remove {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Button.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string FamilySourceSettings_Column_Active {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Column.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FamilySourceSettings_Column_Name {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Column.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string FamilySourceSettings_Column_Source {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Column.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view allows you to create a new family source by selecting from the available source types. Choose the type of family source you want to add from the list, then proceed to configure its settings. This helps you organize and manage your Revit family files according to your preferred source type..
        /// </summary>
        public static string FamilySourceSettings_SelectionView_Description {
            get {
                return ResourceManager.GetString("FamilySourceSettings.SelectionView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view allows you to manage the sources used for Revit family files in the application. You can add new family sources, edit existing ones, or remove sources that are no longer needed. Each source can be activated or deactivated, and you can configure its settings to suit your workflow. Use the controls provided to organize and maintain your family sources efficiently..
        /// </summary>
        public static string FamilySourceSettings_SourcesSettingsView_Description {
            get {
                return ResourceManager.GetString("FamilySourceSettings.SourcesSettingsView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select family source type.
        /// </summary>
        public static string FamilySourceSettings_Text_SelectSourceType {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Text.SelectSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family source settings.
        /// </summary>
        public static string FamilySourceSettings_Window_Title {
            get {
                return ResourceManager.GetString("FamilySourceSettings.Window.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bim.FamilyManager.
        /// </summary>
        public static string Pane_Name {
            get {
                return ResourceManager.GetString("Pane.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bim.FamilyManager settings.
        /// </summary>
        public static string SettingsManager_Window_Title {
            get {
                return ResourceManager.GetString("SettingsManager.Window.Title", resourceCulture);
            }
        }
    }
}
