<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType></OutputType>
	  <TargetFramework>net4.7.2</TargetFramework>
	  <UseWpf>true</UseWpf>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Images\Logo\BIM Family Manager Logo Text.png" Link="Resources\Icons\BimFamilyManagerLogoText.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Images\Logo\BIM Family Manager Logo.ico" Link="Resources\Icons\BimFamilyManagerLogo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<ItemGroup>
    <PackageReference Include="WixSharp-wix4.WPF" Version="2.12.2" />
    <PackageReference Include="WixSharp_wix4" Version="2.12.2" />
  </ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\Icons\" />
	</ItemGroup>

</Project>
