<Project>
  <PropertyGroup>
    <Version>$(GITVERSION_SEMVER)</Version>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>x64</Platforms>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<IsPackable>false</IsPackable>
    	<LangVersion>14.0</LangVersion>
  </PropertyGroup>
  
  <PropertyGroup>
    <!-- Default if nothing provided -->
    <RevitYear Condition="'$(RevitYear)'==''">2025</RevitYear>
  </PropertyGroup>
  
</Project>