<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup Condition="'$(RevitYear)'=='2025'">
        <PackageVersion Include="Nice3point.Revit.Api.AdWindows" Version="2025.4.41" />
        <PackageVersion Include="Nice3point.Revit.Api.RevitAPI" Version="2025.4.41" />
        <PackageVersion Include="Nice3point.Revit.Api.RevitAPIUI" Version="2025.4.41" />
        <PackageVersion Include="Scotec.Revit" Version="[2025.3.3-dev.13,2026)" />
        <PackageVersion Include="Scotec.Revit.Ui" Version="[2025.3.3-dev.13,2026)" />
        <PackageVersion Include="Scotec.Revit.Wpf" Version="[2025.3.3-dev.13,2026)" />
    </ItemGroup>

    <ItemGroup Condition="'$(RevitYear)'=='2026'">
        <PackageVersion Include="Nice3point.Revit.Api.AdWindows" Version="2026.4.0" />
        <PackageVersion Include="Nice3point.Revit.Api.RevitAPI" Version="2026.4.0" />
        <PackageVersion Include="Nice3point.Revit.Api.RevitAPIUI" Version="2026.4.0" />
        <PackageVersion Include="Scotec.Revit" Version="[2026.3.3-dev.13,2027)" />
        <PackageVersion Include="Scotec.Revit.Ui" Version="[2026.3.3-dev.13,2027)" />
        <PackageVersion Include="Scotec.Revit.Wpf" Version="[2026.3.3-dev.13,2027)" />
    </ItemGroup>

    <ItemGroup Condition="'$(RevitYear)'=='2027'">
        <PackageVersion Include="Nice3point.Revit.Api.AdWindows" Version="2027.0.10" />
        <PackageVersion Include="Nice3point.Revit.Api.RevitAPI" Version="2027.0.10" />
        <PackageVersion Include="Nice3point.Revit.Api.RevitAPIUI" Version="2027.0.10" />
        <PackageVersion Include="Scotec.Revit" Version="[2027.3.3-dev.13,2028)" />
        <PackageVersion Include="Scotec.Revit.Ui" Version="[2027.3.3-dev.13,2028)" />
        <PackageVersion Include="Scotec.Revit.Wpf" Version="[2027.3.3-dev.13,2028)" />
    </ItemGroup>

    <ItemGroup>
        <PackageVersion Include="Azure.Storage.Blobs" Version="12.27.0" />
        <PackageVersion Include="Material.Icons.WPF" Version="3.0.2" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
        <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.275" />
        <PackageVersion Include="OpenMcdf" Version="3.1.4" />
        <PackageVersion Include="ScaleHQ.DotScreen" Version="1.0.0-rc.2" />
        <PackageVersion Include="Scotec.Events.WeakEvents" Version="1.1.1" />
        <PackageVersion Include="Scotec.Identity.AzureActiveDirectory" Version="1.1.1" />
        <PackageVersion Include="Scotec.Queues" Version="1.1.1" />
        <PackageVersion Include="Scotec.Wpf" Version="1.0.4-dev.1" />
        <PackageVersion Include="Scotec.Wpf.Controls" Version="1.0.4-dev.1" />
        <PackageVersion Include="System.Drawing.Common" Version="8.0.17" />
        <PackageVersion Include="YamlDotNet" Version="17.1.0" />
    </ItemGroup>

</Project>
