<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>x64</Platforms>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Scotec.Revit" Version="[2025.1.1,2026.0.0)" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.17" />
		<PackageReference Include="Scotec.Wpf" Version="1.0.4-dev.1" />

	</ItemGroup>

</Project>