<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Nice3point.Revit.Api.RevitAPI" />
		<PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" />
		<PackageReference Include="Scotec.Revit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="Scotec.Wpf" />
	</ItemGroup>

</Project>