<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup Condition="'$(RevitYear)'=='2025'">
		<PackageReference Include="Scotec.Revit" Version="[2025.1.1,2026.0.0)" />
	</ItemGroup>

	<ItemGroup Condition="'$(RevitYear)'=='2026'">
		<PackageReference Include="Scotec.Revit" Version="[2026.1.1,2027.0.0)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="8.0.17" />
		<PackageReference Include="Scotec.Wpf" Version="1.0.4-dev.1" />

	</ItemGroup>

</Project>